name: wallie
description: Wallie is a open-source wallpaper app powered by Unsplash API
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_bloc: ^8.1.3
  dio: ^5.3.2
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^4.0.2
  animated_text_kit: ^4.2.2
  transparent_image: ^2.0.1
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  flutter_dotenv: ^5.1.0
  flutter_expandable_fab: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animations/loading_animation.json
    - assets/images/unsplash_logo.png
